version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  data-accessor-vald-web:
    image: data-accessor-vald-web:0.4-SNAPSHOT
    tty: true
    environment:
      - TOPOSOID_VALD_HOST=192.168.33.10
      - TOPOSOID_VALD_PORT=8081
      - TOPOSOID_VALD_DISTANCE_THRESHHOLD=0.05
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - 9010:9010
  vald:
    image: vdaas/vald-agent-ngt:latest
    volumes:
       - ./vald-config:/etc/server
    ports:
      - 8081:8081



