version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  data-accessor-vald-web:
    image: data-accessor-vald-web:0.5-SNAPSHOT
    tty: true
    environment:
      - TOPOSOID_VALD_HOST=172.30.0.3
      - TOPOSOID_VALD_PORT=8081
      - TOPOSOID_VALD_DISTANCE_THRESHHOLD=0.0001
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - 9010:9010
    depends_on:
      - vald
  vald:
    image: vdaas/vald-agent-ngt:v1.7.6
    user: 1001:121
    volumes:
       - ./vald-config:/etc/server
       - /etc/passwd:/etc/passwd:ro
       - /etc/group:/etc/group:ro
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 8081:8081    